#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "use: $0 database0-name database1-name"
    exit 1
fi

DIRECTORY=$(dirname $0)
TMP1=$(mktemp)
TMP2=$(mktemp)

"$DIRECTORY/dmp" "$1" "$3" >"$TMP1"
"$DIRECTORY/dmp" "$2" "$3" >"$TMP2"

diff "$TMP1" "$TMP2"

exit 0
