#!/bin/bash

USER="user"
PASSWORD="1"

if [ "$#" -lt 2 ]; then
	echo "use \"dumpgz database-name dump-file-gz\""
	exit 1
fi

DB_NAME="$1"
DUMP_FILE_GZ="$2"

mariadb-dump --user="$USER" --password="$PASSWORD" "$DB_NAME" | gzip -c >"$DUMP_FILE_GZ"
echo "done - $1"

exit 0
